#!/usr/bin/env python3

import sys
from sys import exit

def print_usage():
    print("""GOcontroll serial number utility
    Usage:
    go-sn [command] 'serial-number'

    Available commands:
    [r]ead      Read the serial number
    [w]rite     Write the 'serial number'

    'serial-number' must be a total of 19 characters long and be segmented into
    4 parts of 4 seperated by '-'

    Examples:
    go-sn read
    go-sn write 1234-5678-9012-3456
    """, file=sys.stderr)

def verify_sn(sn) -> bool:
    if len(sn) != 19:
        return False
    sn_split = sn.split("-")
    for segment in sn_split:
        if len(segment) != 4:
            return False
    return True

args = sys.argv[1:]

try:
    mode = args[0].lower()
except:
    print_usage()
    exit(0)

if mode in "read":
    try:
        with open("/etc/go-sn", "r") as sn_file:
            sn = sn_file.readline().strip()
            if verify_sn(sn):
                print(sn)
                exit(0)
            else:
                print("Invalid serial number read", file=sys.stderr)
                exit(1)
    except FileNotFoundError:
        print("No serial number present to read", file=sys.stderr)
        exit(1)

elif mode in "write":
    try:
        if verify_sn(args[1]):
            sn = args[1]
        else:
            print("invalid serial number entered", file=sys.stderr)
            exit(1)
    except IndexError:
        print("invalid serial number entered", file=sys.stderr)
        exit(-1)
    try:
        with open("/etc/go-sn", "w") as sn_file:
            sn_file.write(sn)
            exit(0)
    except PermissionError:
        print("Could not write serial number", file=sys.stderr)
        exit(1)

